title: "Sbstn Jmnz"
url: https://sbstnjmnz.com
aux_links:
  "Home":
    - "https://sbstnjmnz.com"
  "Empresas":
    - "https://boolean.cl"

aux_links_new_tab: true
github: [metadata]
plugins:
  - jekyll/vite
theme: "just-the-docs"
color_scheme: dark
exclude:
  - bin
  - config
  - vite.config.ts
  - docker-compose.yml
  - package.json
  - package-lock.json
  - exe
  - Rakefile
  - Procfile.dev

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

# For copy button on code
enable_copy_code_button: true

callouts_level: quiet # or loud
callouts:
  highlight:
    title: Atención
    color: yellow
  important:
    title: Importante
    color: blue
  new:
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Peligro
    color: red
    
# Define Jekyll collections
collections:
  # Define a collection named "tests", its documents reside in the "_tests" directory
  javascript:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    javascript:
      # Give the collection a name
      name: Javascript
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      # nav_fold: true  # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true
