title: Sebastian Jimenez
desc: Software Engineer
email: sbstn.jmnz@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Personal site about software and industrial engeneering.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sbstn-jmnz
linkedin_username: sebastián-jiménez-olguín-695a8828
google_analytics: UA-58311145-2
collections:
    javascript:
      output: true
    solid:
      output: true
        
sass:
    sass_dir: _sass
    style: compressed
gems:
 - jekyll-coffeescript
# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
